### ISSUE TITLE
Atari Pong dreamer.py not working with 16bit precision: "No inf checks were recorded for this optimizer" error

### ISSUE THREAD

**Issue by dosssman** [jsikyoon/dreamer-torch#2]
Greetings.

Thank you very much for your work on porting the original TF2 implementation to pytorch, as well as open sourcing it.
I have recently been looking over this kind of project that port Dreamer-v1 / v2 to Pytorch for some experiment in my research, hence my interest in your code.

I was wondering if you had some insight on the follow problems I ran into when trying to run the code from this repository.

## 1. 16 bit precision error.

As a first try, I attempted to execute the default dreamer agaent on Atari's Pong, running the same command as in the original implementation: `python3 dreamer.py --logdir ~/logdir/atari_pong/dreamerv2/1   --configs defaults atari --task atari_pong`.
However, after the experience buffer was pre-filled and training is about to start, the scirpts returns the following error which seems to be related to Torch's AMP, which I understand as being related to the mixed precision computation:
```bash
(dreamer-torch) dreamer-torch$ python dreamer.py --logdir ./logdir/atari_pong/dreamerv2/2 --configs defaults atari --task atari_pong
Logdir logdir/atari_pong/dreamerv2/2
Create envs.
Prefill dataset (0 steps).
Eval episode has 934 steps and return -20.0.
[201372] eval_return -20.0 / eval_length 934.0 / eval_episodes 1.0
Invalid MIT-MAGIC-COOKIE-1 keySimulate agent.
[201372] 
Start evaluation.
Eval episode has 832 steps and return -20.0.
[201372] eval_return -20.0 / eval_length 832.0 / eval_episodes 1.0
Start training.
[201372] fps 0.0
Traceback (most recent call last):
  File "dreamer.py", line 317, in <module>
    main(parser.parse_args(remaining))
  File "dreamer.py", line 295, in main
    state = tools.simulate(agent, train_envs, config.eval_every, state=state)
  File "/home/d055/random/rl/dreamer-torch/tools.py", line 136, in simulate
    action, agent_state = agent(obs, done, agent_state, reward)
  File "dreamer.py", line 75, in __call__
    self._train(next(self._dataset))
  File "dreamer.py", line 144, in _train
    metrics.update(self._task_behavior._train(start, reward)[-1])
  File "/home/d055/random/rl/dreamer-torch/models.py", line 207, in _train
    metrics.update(self._actor_opt(actor_loss, self.actor.parameters()))
  File "/home/d055/random/rl/dreamer-torch/tools.py", line 481, in __call__
    self._scaler.step(self._opt)
  File "/home/d055/anaconda3/envs/dreamer-torch/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 337, in step
    assert len(optimizer_state["found_inf_per_device"]) > 0, "No inf checks were recorded for this optimizer."
AssertionError: No inf checks were recorded for this optimizer.
```

Do you happen to have any idea on why this might be ?

I am using Python 3.8.12, and installed the dependencies using `pip install -r requirements.txt` provided in the repository.

## 2. Little out of topic issue: using 32 bit precision

I tried to play with the precision the scripts use for their computation by setting `--precision 32` (to my understanding, this is the default precision of Pytorch), and the code does end up running without the previous error.
However, even after training the agent for around 16 millions steps, there is not improvement in performance, unlike the curves you have provided for Atari pong.
I was thus wondering if the change of the precision might have been the reason for this, and would be interested to know your opinion about it, as well as any recommendation for running the code in this repository to at least reproduce the original paper's result.

Thank you very much for your time.
Looking forward to hear back from you.
Best regards.

**Comment by jsikyoon** [comment]
Hi Dosssman,

Thank you for your interest in my implementation.

First of all, I will try to reproduce your problem on my side. 

I don't think the performance issue (your second question) is not related to precision configuration (As I experienced, the Pong game might be okay to be learned). 

In those days, I changed my codes a little for optimization and clean-up, that could be the reason. Anyway, I will check and leave my results on here soon.

Thank you again!
Bests, Jaesik.

**Comment by dosssman** [comment]
Thank very much you for your fast answer!

Looking forward to hear more about your result with 16 bit experiments then.

**Comment by jsikyoon** [comment]
I found a bug when calculating gradient on the imagination part, I fixed and uploaded the fixed version. 
https://github.com/jsikyoon/dreamer-torch/commit/e588aa2606c78b1e82115eec4412df74f9dbc9ae 

Your first problem is gone.

I am running atari pong with precision 32 and 16 configurations, I will share the results.

Thanks!!
Bests, Jaesik.

**Comment by jsikyoon** [comment]
I checked my updated version is not working for atari pong, and update it similar to the previous version.

However, it is also not working with the precision=16 option, I cannot find the reason on my codes T_T

<img width="353" alt="Screen Shot 2022-01-20 at 10 27 52 AM" src="https://user-images.githubusercontent.com/22428579/150245678-b8d17c52-8f43-4100-bc50-d6177a4d5f23.png">

Pink is with precision 32, sky-blue is with precision 16.

**Comment by dosssman** [comment]
Hello.

Thank you very much for looking into this. It is unfortunate that the 16 bit version does not seems to work.
I suspect that depending on the tasks, the observed values as the reward prediction, probability estimation, expected return, and small valued gradients lead to not precise enough results, which could hurt the learning of the agent. I guess there might be some additional tuning required to support 16 bit precision on torch.

While the original author's implementation does seem to work with 16 bit, the implementation of mixed precision in TF and Torch might differ enough to also be a contributing factor.

Fortunately, the 32 bit version seems to work well enough. I have also tested on my side, the same way you did, and get similar results.

![image](https://user-images.githubusercontent.com/21224272/150453578-fe5b0c1a-4036-48b7-a501-dde874ed5368.png)
![image](https://user-images.githubusercontent.com/21224272/150453625-1462850b-fb23-415d-aed6-1a1b1b76cdfb.png)

Again, hank you very much for taking the time to look into this.
I will be referencing your code during my experiments using 32 bits as default for now.
I will be closing this issue, in any case.
Let's keep up the good work.

**Comment by zdx3578** [comment]
python 3.10 install gym error

**Comment by zdx3578** [comment]
python3.9 ok;; install req.txt  ok;
