### ISSUE TITLE
Bug about GRU

### ISSUE THREAD

**Issue by TachikakaMin** [jsikyoon/dreamer-torch#3]
https://github.com/jsikyoon/dreamer-torch/blob/e588aa2606c78b1e82115eec4412df74f9dbc9ae/networks.py#L175

CUDA_VISIBLE_DEVICES=0 python dreamer.py --logdir logdir/walker/dreamerv2/1 --configs defaults

defaults:
  dyn_cell: 'gru'

It will cause bug.

**Comment by jsikyoon** [comment]
I didn't check the option, I will do that.

Thanks!

**Comment by jsikyoon** [comment]
fixed this bug with https://github.com/jsikyoon/dreamer-torch/commit/e42d504ea362ad605c7bbe2a0d89df1d2b3e07f2 

Thanks!
