### ISSUE TITLE
Actor and value loss: actor entropy and state entropy addition during the ImagBehavior update

### ISSUE THREAD

**Issue by dosssman** [jsikyoon/dreamer-torch#6]
Greetings.
Thank you very much for your assistance last time regarding the `precion=32` issue #2
Your implementation has been a great reference for me.

This issue is not so much of an issue, and more of a query about the logic for the actor update.

Namely, when [training](https://github.com/jsikyoon/dreamer-torch/blob/e42d504ea362ad605c7bbe2a0d89df1d2b3e07f2/models.py#L168) the `ImagBehavior` component of Dreamer at line, the `target` and `weights` are first computed using `_compute_target` [method](https://github.com/jsikyoon/dreamer-torch/blob/e42d504ea362ad605c7bbe2a0d89df1d2b3e07f2/models.py#L236).
In `_compute_target`, in case the `actor entropy` and `state entropy` flags are enabled, they are respectively added to the predicted imaginated reward list, as per the following lines https://github.com/jsikyoon/dreamer-torch/blob/e42d504ea362ad605c7bbe2a0d89df1d2b3e07f2/models.py#L236-L247

Then, before the `actor_loss` itself is computed in [`_compute_actor_loss`](https://github.com/jsikyoon/dreamer-torch/blob/e42d504ea362ad605c7bbe2a0d89df1d2b3e07f2/models.py#L259), the `actor_entropy` and `state_entropy` are added one more time as per the following lines;
https://github.com/jsikyoon/dreamer-torch/blob/e42d504ea362ad605c7bbe2a0d89df1d2b3e07f2/models.py#L280-L283

From my perspective, it looks like the entropy bonus is added twice in total, and I was wondering if you have any insights on why it is done like so?

Looking forward to hear back from you again, and in the mean time
Best regards.

**Comment by dosssman** [comment]
I am not sure if my understanding is correct, but in danijar/dreamerv2 repository, the actor entropy is only added in the `actor_loss` [method](https://github.com/danijar/dreamerv2/blob/3a711b42461b9942396f84ad3a63ec00f25faedb/dreamerv2/agent.py#L252)  as follows:

https://github.com/danijar/dreamerv2/blob/3a711b42461b9942396f84ad3a63ec00f25faedb/dreamerv2/agent.py#L252-L290

while the `target` method seems to not have anything related to actor nor state entropy:

https://github.com/danijar/dreamerv2/blob/3a711b42461b9942396f84ad3a63ec00f25faedb/dreamerv2/agent.py#L306-L324

**Comment by jsikyoon** [comment]
Hi, dosssman,

sorry for the late reply.

I checked the parts.

That is based on the TFv2 codes, https://github.com/danijar/dreamerv2/blob/faf9e4c606e735f32c8b971a3092877265e49cc2/models.py#L206-L211.

And, he used future_entropy configuration, which roles to decide when adding the entropy in compute_target or compute_actor_loss functions.

So, the double addition doesn't happen (when future_entropy=True, entropy is added when computing target, while it is added when computing actor_target when future_entropy=False).

Please feel free to let me know if you have any other issues!!

Bests, Jaesik.

**Comment by dosssman** [comment]
Ah, I see. Somehow I did not pick up the if not `self._config.future_entropy` so it looked the same for me.
Thank you very much for taking your time to point this out.

Another point I was curious about is the influence of the `state_ent`.
I assume this is to give a bonus for the actor to visit more diverse states, but I could not find anything related to this component in the paper. There seems to be only `actor_entropy` based regularization. 
Especially if I refer to the current commit, `state_ent` seems to be [gone](https://github.com/danijar/dreamerv2/blob/3a711b42461b9942396f84ad3a63ec00f25faedb/dreamerv2/agent.py#L285)

Do you have any insights regarding this part by any chance ?

EDIT: According to the [paper](https://arxiv.org/pdf/2010.02193v3.pdf), "future_entropy"which seems to be referred to as long-term entropy did not help substancially.
That might be why it was removed from the most recent version ...
![image](https://user-images.githubusercontent.com/21224272/152895885-4785ec32-e64d-4b3c-a985-a4b334b3c0ce.png)
(Appendix C, P18)

**Comment by jsikyoon** [comment]
I think that he removed some parameters which were not helpful including state_ent and long-term entropy or other things (he changed the default actor loss from mixed to reinforce as I know).

**Comment by dosssman** [comment]
Indeed. The final version looks much simpler.
In any case, thanks again for helping me understanding those parts.
Have a nice day.
